### PR TITLE
feat: add issues permission to release workflow

### PR DESCRIPTION
**Pull request by fritzy**

### CODE REVIEW

**Comment by fritzy** [comment]
Should probably be squashed.

**Comment by lukekarrys** [comment]
After a bit more investigation, I'm not sure if the original failing workflow in [`npm/cli`](https://github.com/npm/cli/actions/runs/4071227938/jobs/7012840616#step:6:805) is a permissions issue.

All of our repos use the same action and I've seen some succeed and some fail with the latest version of template-oss:

- `stafftools` failed: https://github.com/npm/stafftools/actions/runs/4109009588/jobs/7090345220#step:8:121
- `ignore-walk` succeeded: https://github.com/npm/ignore-walk/pull/70

I haven't root caused the issue but I did add some logging in #277 which should help the next time it fails.

**Review by lukekarrys — COMMENTED** [review]
After a bit more investigation, I'm not sure if the original failing workflow in [`npm/cli`](https://github.com/npm/cli/actions/runs/4071227938/jobs/7012840616#step:6:805) is a permissions issue.

All of our repos use the same action and I've seen some succeed and some fail with the latest version of template-oss:

- `stafftools` failed: https://github.com/npm/stafftools/actions/runs/4109009588/jobs/7090345220#step:8:121
- `ignore-walk` succeeded: https://github.com/npm/ignore-walk/pull/70

I haven't root caused the issue but I did add some logging in #277 which should help the next time it fails.

**Comment by lukekarrys** [comment]
The latest CLI release worked, so I'm chalking up the previous failure to "GitHub actions weirdness"

**Pull request closed without merging**
